### ISSUE TITLE
Docker Image Not Mainnet

### ISSUE THREAD

**Issue by joesixpack** [quantadex/quanta-core#8]
I followed the directions for switching to mainnet at gitbook (and additionally commented out the trusted-node), but the Chain ID remains that of the testnet.

**Comment by quocble** [comment]
Try:   https://cloud.docker.com/u/quantalabs/repository/docker/quantalabs/quanta-core
107m (m for mainnet)

**Comment by joesixpack** [comment]
That link is broken, BTW, but I did try 107m and it still did not change the Chain ID.

**Comment by quocble** [comment]
Sorry about that, i gave you an internal link, here's the public link: https://hub.docker.com/r/quantalabs/quanta-core/tags

I don't think we have the seeds node built into the binary so you have to setup the correct configuration as well: 

Change the config.ini, change the seed-nodes to these ips:

```
seed-nodes = ["35.206.87.178:4600","54.203.105.154:4600"]
```

 Make sure you wipe out the data directory before you restart.
